import { FormatButton } from '../types'

export const FORMAT_BUTTONS: FormatButton[] = [
  { id: 'sep0', icon: '', titleKey: '', type: 'sep' },
  { id: 'bold', icon: 'B', titleKey: 'format.bold', type: 'wrap', value: '**' },
  { id: 'italic', icon: 'I', titleKey: 'format.italic', type: 'wrap', value: '*' },
  { id: 'underline', icon: 'U', titleKey: 'format.underline', type: 'wrap', value: '<u>' },
  { id: 'strike', icon: 'S', titleKey: 'format.strikethrough', type: 'wrap', value: '~~' },
  { id: 'sub', icon: 'A₂', titleKey: 'format.subscript', type: 'wrap', value: '<sub>' },
  { id: 'sup', icon: 'A²', titleKey: 'format.superscript', type: 'wrap', value: '<sup>' },
  { id: 'sep1', icon: '', titleKey: '', type: 'sep' },
  { id: 'h1', icon: 'H1', titleKey: 'format.h1', type: 'line', value: '# ' },
  { id: 'h2', icon: 'H2', titleKey: 'format.h2', type: 'line', value: '## ' },
  { id: 'h3', icon: 'H3', titleKey: 'format.h3', type: 'line', value: '### ' },
  { id: 'sep2', icon: '', titleKey: '', type: 'sep' },
  { id: 'color', icon: 'A', titleKey: 'format.textColor', type: 'color' },
  { id: 'bgColor', icon: 'H', titleKey: 'format.highlight', type: 'bgColor' },
  { id: 'link', icon: '', titleKey: 'format.link', type: 'link' },
  { id: 'sep3', icon: '', titleKey: '', type: 'sep' },
  { id: 'align-left', icon: '', titleKey: 'format.alignLeft', type: 'align', value: 'left' },
  { id: 'align-center', icon: '', titleKey: 'format.alignCenter', type: 'align', value: 'center' },
  { id: 'align-right', icon: '', titleKey: 'format.alignRight', type: 'align', value: 'right' },
  { id: 'align-justify', icon: '', titleKey: 'format.alignJustify', type: 'align', value: 'justify' },
  { id: 'sep4', icon: '', titleKey: '', type: 'sep' },
  { id: 'quote', icon: '"', titleKey: 'format.quote', type: 'line', value: '> ' },
  { id: 'code', icon: '<>', titleKey: 'format.code', type: 'wrap', value: '`' },
  { id: 'codeblock', icon: '', titleKey: 'format.codeBlock', type: 'codeblock' },
  { id: 'sep5', icon: '', titleKey: '', type: 'sep' },
  { id: 'ul', icon: '-', titleKey: 'format.ul', type: 'line', value: '- ' },
  { id: 'ol', icon: '1.', titleKey: 'format.ol', type: 'line', value: '1. ' },
  { id: 'sep6', icon: '', titleKey: '', type: 'sep' },
  { id: 'hr', icon: '—', titleKey: 'format.hr', type: 'block', value: '\n---\n' },
  { id: 'sep7', icon: '', titleKey: '', type: 'sep' },
  { id: 'fontFamily', icon: 'Aa', titleKey: 'format.fontFamily', type: 'fontFamily' },
  { id: 'fontSize', icon: 'T', titleKey: 'format.fontSize', type: 'fontSize' },
]

export const MARKER_CLOSERS: Record<string, string> = {
  '**': '**',
  '*': '*',
  '<u>': '</u>',
  '~~': '~~',
  '<sub>': '</sub>',
  '<sup>': '</sup>',
  '`': '`',
}
